CREATE DATABASE TP_FINAL_CALLCENTER;
USE TP_FINAL_CALLCENTER;

CREATE TABLE ESTADO_CLIENTE (
	TIPO_ESTADO VARCHAR(3) NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(200) UNIQUE,
);

CREATE TABLE PERSONA (
	DOCUMENTO INT NOT NULL ,
	TIPO_DOC CHAR(4) NOT  NULL ,
	NOMBRE VARCHAR(15),
	APELLIDO VARCHAR(15),
	ESTADO_CLIENTE VARCHAR(3) NOT NULL FOREIGN KEY REFERENCES ESTADO_CLIENTE(TIPO_ESTADO),
	EMAIL VARCHAR(120),
	FECHA_NAC DATE,
	CONSTRAINT PK_PERSONAS PRIMARY KEY (TIPO_DOC,DOCUMENTO),
);

CREATE TABLE TIPO_SERVICIO (
	TIPO VARCHAR(12) NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(150) UNIQUE,
);

CREATE TABLE SERVICIO (
	NRO_SERVICIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TELEFONO INT, 
	DIRECCION VARCHAR(70) NOT NULL,
	FECHA_INICIO DATE,
	ESTADO VARCHAR(10), 
	TIPO_DOC_PERSONA CHAR(4) NOT NULL,
	DOC_PERSONA INT NOT NULL,
	TIPO_SERVICIO VARCHAR(12) FOREIGN KEY REFERENCES TIPO_SERVICIO(TIPO),
	FOREIGN KEY (TIPO_DOC_PERSONA,DOC_PERSONA) REFERENCES PERSONA(TIPO_DOC,DOCUMENTO),
);


CREATE TABLE TIPOLOGIA (
	MOTIVO VARCHAR(45) NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(150) UNIQUE,
);


CREATE TABLE TIPOLOGIA_TIPO_SERVICIO (
	TIPOLOGIA VARCHAR(45) NOT NULL FOREIGN KEY REFERENCES TIPOLOGIA(MOTIVO),
	TIPO_SERVICIO VARCHAR(12) NOT NULL FOREIGN KEY REFERENCES TIPO_SERVICIO(TIPO),
	SLA INT NOT NULL,
	PRIMARY KEY (TIPOLOGIA, TIPO_SERVICIO),
);

CREATE TABLE EMPLEADO (
	ID_LEGAJO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(45),
	APELLIDO VARCHAR(45),
	ESTADO VARCHAR(10),
	LOGIN VARCHAR(45) UNIQUE,
);

CREATE TABLE TICKET (
	ID_TICKET INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIPOLOGIA VARCHAR(45) NOT NULL FOREIGN KEY REFERENCES TIPOLOGIA(MOTIVO),
	EMPLEADO INT NOT NULL FOREIGN KEY REFERENCES EMPLEADO(ID_LEGAJO),
	TIPO_DOC_PERSONA CHAR(4) NOT NULL,
	DOC_PERSONA INT NOT NULL,
	SERVICIO INT FOREIGN KEY REFERENCES SERVICIO(NRO_SERVICIO),
	ESTADO VARCHAR(45),
	FECHA_APERTURA DATETIME,
	FECHA_CIERRE DATETIME,
	FECHA_RESOLUC DATETIME,
	FOREIGN KEY (TIPO_DOC_PERSONA,DOC_PERSONA) REFERENCES PERSONA(TIPO_DOC,DOCUMENTO)
);

CREATE TABLE MENSAJE (
	ID_MENSAJE INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ESTADO VARCHAR(45),
	TICKET INT NOT NULL FOREIGN KEY REFERENCES TICKET(ID_TICKET),
	TEXTO VARCHAR(45),
	DESTINATARIO VARCHAR(120),
);

CREATE TABLE HISTORIAL (
	ID_HISTORIAL INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ESTADO VARCHAR(45),
	TICKET INT NOT NULL FOREIGN KEY REFERENCES TICKET(ID_TICKET),
	FECHA_MODIF DATETIME,
	FECHA_INICIO DATETIME,
	FECHA_FIN DATETIME,
);

CREATE TABLE ACTIVIDAD (
	ID_ACTIVIDAD INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ESTADO VARCHAR(10),
	TICKET INT NOT NULL FOREIGN KEY REFERENCES TICKET(ID_TICKET),
	TIPO VARCHAR(45),
);

