CREATE  VIEW VIEW_SLA AS
SELECT ID_TICKET, TIPOLOGIA, EMPLEADO, TIPO_DOC_PERSONA, DOC_PERSONA, SERVICIO, FECHA_APERTURA, FECHA_CIERRE, FECHA_RESOLUC
FROM TICKET T inner join HISTORIAL H on t.ID_TICKET = H.TICKET
WHERE DATEDIFF(DAY, (Select FECHA_INICIO from historial where h.ticket = t.ID_TICKET AND ESTADO = 'PENDIENTE CLIENTE') , (Select FECHA_FIN from historial where h.ticket = t.ID_TICKET AND ESTADO = 'PENDIENTE CLIENTE'))
< (SELECT SLA FROM TIPOLOGIA_TIPO_SERVICIO TTS WHERE TTS.TIPOLOGIA = T.TIPOLOGIA AND (SELECT TIPO_SERVICIO FROM SERVICIO WHERE NRO_SERVICIO = T.SERVICIO) = TTS.TIPO_SERVICIO)

SELECT * FROM VIEW_SLA